Created Contact Form
AsimKhan2019/HTML_Mobile_Exercise pull request #11
Opened 2022-05-31 14:34 UTC by AsimKhan2019

Created a contact form as part of the exercise today. Applied flex properties to the section elements of the form and worked on alignment and spacing. 

Integrated Form Spree to the form of the contact section, and added the necessary attributes and max length characters to handle the limit. Also, all the inputs are required fields.

2022-05-31 14:44 UTC, arslanbisharat requested changes
Hi @AsimKhan2019, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- [x] Pull Request is descriptive. 
- [ ] Readme is well written. 
- [ ] All technical aspects of the project has been completed. 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 14:44 UTC, arslanbisharat commented on style.css
> +#contact {
- [ ] Let's not use IDs in your CSS. It's recommended to use classes instead.

2022-05-31 14:44 UTC, arslanbisharat commented on style.css
> +#contact h1 {
- [ ] Let's not use IDs in your CSS. It's recommended to use classes instead.

2022-05-31 14:44 UTC, arslanbisharat commented on style.css
> +#contact form {
- [ ] Let's not use IDs in your CSS. It's recommended to use classes instead.

2022-05-31 14:44 UTC, arslanbisharat commented on style.css
> +#contact p {
- [ ] Let's not use IDs in your CSS. It's recommended to use classes instead.

2022-05-31 14:44 UTC, arslanbisharat commented on style.css
> +#contact form input {
- [ ] Let's not use IDs in your CSS. It's recommended to use classes instead.

2022-05-31 14:44 UTC, arslanbisharat commented on style.css
> +#contact form textarea {
- [ ] Let's not use IDs in your CSS. It's recommended to use classes instead.

2022-05-31 14:44 UTC, arslanbisharat commented on style.css
> +#contact form .primary-btn {
- [ ] Let's not use IDs in your CSS. It's recommended to use classes instead.

2022-05-31 14:44 UTC, arslanbisharat commented on style.css
> +
- [ ] Let's not use IDs in your CSS. It's recommended to use classes instead.

2022-05-31 14:44 UTC, arslanbisharat commented on style.css
> +#contact form .primary-btn:active {
- [ ] Let's not use IDs in your CSS. It's recommended to use classes instead.

2022-05-31 14:44 UTC, arslanbisharat commented on index.html
> +                Contact me
- [ ] You have commented code at `13`, `18`, `21`, and `41`. Please remove it.

2022-05-31 14:53 UTC, AsimKhan2019 commented on style.css
> +#contact {
@arslanbisharat Thank you for the review. Kindly please review the updated code.

2022-05-31 14:54 UTC, AsimKhan2019 commented on style.css
> +#contact h1 {
@arslanbisharat Thank you for the review. Kindly please review the updated code.

2022-05-31 14:54 UTC, AsimKhan2019 commented on style.css
> +#contact form {
@arslanbisharat Thank you for the review. Kindly please review the updated code.

2022-05-31 14:54 UTC, AsimKhan2019 commented on style.css
> +#contact p {
@arslanbisharat Thank you for the review. Kindly please review the updated code.

2022-05-31 14:54 UTC, AsimKhan2019 commented on style.css
> +#contact form textarea {
@arslanbisharat Thank you for the review. Kindly please review the updated code.

2022-05-31 14:54 UTC, AsimKhan2019 commented on style.css
> +#contact form .primary-btn {
@arslanbisharat Thank you for the review. Kindly please review the updated code.

2022-05-31 14:54 UTC, AsimKhan2019 commented on style.css
> +
@arslanbisharat Thank you for the review. Kindly please review the updated code.

2022-05-31 14:54 UTC, AsimKhan2019 commented on style.css
> +#contact form .primary-btn:active {
@arslanbisharat Thank you for the review. Kindly please review the updated code.

2022-05-31 14:55 UTC, AsimKhan2019 commented on index.html
> +                Contact me
@arslanbisharat Thank you for the review. Kindly please review the updated code.

2022-05-31 15:23 UTC, AsimKhan2019 reviewed
Changed the #contact ID in the style.css file to .contact Class. As advised by fellow Micronaut.

2022-05-31 15:23 UTC, AsimKhan2019 commented on style.css
> +.contact {
- [ ] Changed #contact ID to .contact class.

2022-06-01 06:50 UTC, AsimKhan2019 commented
@KayLemba Thank you for the feedback

2022-06-01 06:50 UTC, merged